server:
  port: 8081
  servlet:    context-path: /spring-boot
person:
    #lastName: zhangsan
    age: 23
    boss: false
    birth: 2019/1/1
    dog:
       name: 小狗
       age: 1
    lists:
        - lisi
        - zhaoliu
    maps:
       {k1: v1,k2: v2}    last-name: 小明
  