server:
  port: 8081
  servlet:    context-path: /spring-boot
spring:
  profiles:
    active: prod
---
server:  port: 8082
spring:
  profiles: dev
---
server:  port: 8083
spring:  profiles: prod
  